import Head from 'next/head'
import HeroAgency from '../components/main-page/hero-agency/HeroAgency'
import VideoFeature from '../components/main-page/video-feature/VideoFeature'
import Services from '../components/main-page/services/Services'
import CallToAction from '../common/call-to-action/CallToAction'
import Portfolio from '../components/main-page/portfolio/Portfolio'
import Testimonials from '../components/main-page/testimonials/Testimonials'
import Counterup from '../components/main-page/counterup/Counterup'
import OurTeam from '../components/main-page/our-team/OurTeam'
import LatestBlog from '../components/main-page/latest-blog/LatestBlog'
import ClientArea from '../components/main-page/client-area/ClientArea'
export default function Home() {
  return (
    <div id="bg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
      </Head>
      <div id="page" className="site">
        <HeroAgency />
        <VideoFeature />
        <Services />
        <CallToAction
            content={{
              title: 'محصولات و خلاقیت مارک مد ماست',
              discription: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و
            با استفاده از طراحان گرافیک است`,
              button: 'نمونه کارها',
            }}
        />
        <Portfolio />
        <Testimonials />
        <Counterup />
        <OurTeam />
        <LatestBlog />
        <ClientArea />
      </div>
    </div>
  )
}